from typing import List

from pydantic import BaseModel, Field

from dotenv import load_dotenv
load_dotenv()

from langchain.agents import create_agent 
from langchain.tools import tool 
from langchain_core.messages import HumanMessage 
from langchain_groq import ChatGroq
from langchain_tavily import TavilySearch 

class Source(BaseModel):
    """
    Schema for the source used by the agent
    """
    url:str = Field(description="The URL of the source")

class AgentResponse(BaseModel):
    """ Schema for agent response with answer and sources """

    answer:str = Field(description="The answer generated by the agent")
    sources:List[Source]= Field(default_factory=list, description="The list of sources used by the agent to generate the answer")



llm = ChatGroq(model = "openai/gpt-oss-120b" )
tools = [TavilySearch()]
agent = create_agent(model = llm, tools = tools, response_format = AgentResponse) 


def main():
    print("Hello from langchain-course!")
    result = agent.invoke ({"messages":HumanMessage(content='Search for 3 job postings for an ai engineer using langchain in the bay area on linkedin and list their details')})
    print(result)
    


if __name__ == "__main__":
    main()
